create schema kino_cms;

use kino_cms;
INSERT INTO User (name, surname, nickname, email, address, password, card_number, language, gender, phone_number, date_of_birth, city)
VALUES ('John', 'Doe', 'johndoe', 'user1@example.com', '123 Main St', '0000', '1234567890123456', 'Русский', 'MALE', '1234567890', '1990-01-01', 'New York'),
       ('Jane', 'Smith', 'janesmith', 'user2@example.com', '456 Elm St', '000', '9876543210987654', 'Русский', 'FEMALE', '9876543210', '1995-02-15', 'Paris');

insert into main_page(id,
                      phone_number,
                      phone_number2,
                      seo_description,
                      seo_keywords,
                      seo_title,
                      seo_url,
                      status,
                      date_of_created)
    VALUES (1, '+7 (999) 999-99-99',
            '+7 (888) 888-88-88',
            'This is the SEO description of the main page.',
            'This is the SEO keywords of the main page.',
            'This is the SEO title of the main page.',
            'main-page',
            'ACTIVE',
            '2020-01-01');

insert into page (description,
                  main_image,
                  name,
                  seo_description,
                  seo_keywords,
                  seo_title,
                  seo_url,
                  status,
                  date_of_created)
VALUES ('This is the description of the first page.',
        'This is the main image of the first page.',
        'О кинотеатре',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01'),
       ('This is the description of the second page.',
        'This is the main image of the second page.',
        'Кафе - Бар',
        'This is the SEO description of the second page.',
        'This is the SEO keywords of the second page.',
        'This is the SEO title of the second page.',
        'second-page',
        true,
        '2020-01-01'),
       ('This is the description of the first page.',
        'This is the main image of the first page.',
        'Vip - зал',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01'),
       ('This is the description of the first page.',
        'This is the main image of the first page.',
        'Реклама',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01'),
       ('This is the description of the first page.',
        'This is the main image of the first page.',
        'Детская комната',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01');

insert into contact_page(id,
                         link_video,
                         seo_description,
                         seo_keywords,
                         seo_title,
                         seo_url,
                         date_of_created)
    VALUE (1, 'https://www.youtube.com/embed/dQw4w9WgXcQ',
           'This is the SEO description of the contact page.',
           'This is the SEO keywords of the contact page.',
           'This is the SEO title of the contact page.',
           'contact-page',
           '2020-01-01');

insert into contact_cinema(id,
                           address,
                           location,
                           logo,
                           name,
                           status,
                           contact_page_id)
    value (1,
           'г. Москва, ул. Ленина, д. 1',
           'Москва',
           'logo.png',
           'Кинотеатр "Кино"',
           'ACTIVE',
           1);

