use kino_cms;
INSERT INTO User (name, surname, nickname, email, address, password, card_number, language, gender, phone_number,
                  date_of_birth, city)
VALUES ('John', 'Doe', 'johndoe', 'user1@example.com', '123 Main St', '0000', '1234567890123456', 'Русский', 'MALE',
        '1234567890', '1990-01-01', 'New York'),
       ('Jane', 'Smith', 'janesmith', 'user2@example.com', '456 Elm St', '0000', '9876543210987654', 'Русский',
        'FEMALE', '9876543210', '1995-02-15', 'Paris');

insert into main_page(id,
                      phone_number,
                      phone_number2,
                      seo_description,
                      seo_keywords,
                      seo_title,
                      seo_url,
                      status,
                      date_of_created)
VALUES (1,
        '1234567890',
        '9876543210',
        'This is the SEO description of the main page.',
        'This is the SEO keywords of the main page.',
        'This is the SEO title of the main page.',
        'main-page',
        true,
        '2020-01-01');


insert into page (description,
                  main_image,
                  name,
                  seo_description,
                  seo_keywords,
                  seo_title,
                  seo_url,
                  status,
                  date_of_created)
VALUES ('This is the description of the first page.',
        'This is the main image of the first page.',
        'О кинотеатре',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01'),
       ('This is the description of the second page.',
        'This is the main image of the second page.',
        'Кафе - Бар',
        'This is the SEO description of the second page.',
        'This is the SEO keywords of the second page.',
        'This is the SEO title of the second page.',
        'second-page',
        true,
        '2020-01-01'),
       ('This is the description of the first page.',
        'This is the main image of the first page.',
        'Vip - зал',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01'),
       ('This is the description of the first page.',
        'This is the main image of the first page.',
        'Реклама',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01'),
       ('This is the description of the first page.',
        'This is the main image of the first page.',
        'Детская комната',
        'This is the SEO description of the first page.',
        'This is the SEO keywords of the first page.',
        'This is the SEO title of the first page.',
        'first-page',
        true,
        '2020-01-01');

insert into contact_page(id, date_of_created, link_video, name, seo_description,
                         seo_keywords, seo_title, seo_url, status)
VALUES (1,
        '2020-01-01',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        'Контакты',
        'This is the SEO description of the contact page.',
        'This is the SEO keywords of the contact page.',
        'This is the SEO title of the contact page.',
        'contact-page',
        true);



insert into stock (id,
                   date_created,
                   date_posting,
                   description,
                   link_video,
                   main_image,
                   name,
                   seo_description,
                   seo_keywords,
                   seo_title,
                   seo_url,
                   status)
    value (1,
           '2020-01-01',
           '2020-01-01',
           'This is the description of the first stock.',
           'https://www.youtube.com/embed/dQw4w9WgXcQ',
           'This is the main image of the first stock.',
           'First Stock',
           'This is the SEO description of the first stock.',
           'This is the SEO keywords of the first stock.',
           'This is the SEO title of the first stock.',
           'first-stock',
           true),
    (2,
     '2020-01-01',
     '2020-01-01',
     'This is the description of the second stock.',
     'https://www.youtube.com/embed/dQw4w9WgXcQ',
     'This is the main image of the second stock.',
     'Second Stock',
     'This is the SEO description of the second stock.',
     'This is the SEO keywords of the second stock.',
     'This is the SEO title of the second stock.',
     'second-stock',
     true);

insert into news (id,
                  date_created,
                  date_posting,
                  description,
                  link_video,
                  main_image,
                  name,
                  seo_description,
                  seo_keywords,
                  seo_title,
                  seo_url,
                  status)
    VALUE (
           1,
           '2020-01-01',
           '2020-01-01',
           'This is the description of the first news.',
           'https://www.youtube.com/embed/dQw4w9WgXcQ',
           'This is the main image of the first news.',
           'First News',
           'This is the SEO description of the first news.',
           'This is the SEO keywords of the first news.',
           'This is the SEO title of the first news.',
           'first-news',
           true
    ),
    (
     2,
     '2020-01-01',
     '2020-01-01',
     'This is the description of the first news.',
     'https://www.youtube.com/embed/dQw4w9WgXcQ',
     'This is the main image of the first news.',
     'First News',
     'This is the SEO description of the first news.',
     'This is the SEO keywords of the first news.',
     'This is the SEO title of the first news.',
     'first-news',
     true
        );

insert into cinemas (id, conditions,
                     description, logo_path,
                     name, seo_description,
                     seo_keywords, seo_title,
                     seo_url,
                     top_banner)
VALUES (1,
        'This is the description of the first cinema.',
        'This is the logo of the first cinema.',
        'first-cinema',
        'First Cinema',
        'This is the SEO description of the first cinema.',
        'This is the SEO keywords of the first cinema.',
        'This is the SEO title of the first cinema.',
        'first-cinema',
        'This is the top banner of the first cinema.'),
       (2,
        'This is the description of the second cinema.',
        'This is the logo of the second cinema.',
        'second-cinema',
        'Second Cinema',
        'This is the SEO description of the second cinema.',
        'This is the SEO keywords of the second cinema.',
        'This is the SEO title of the second cinema.',
        'second-cinema',
        'This is the top banner of the second cinema.');

insert into hall (id,
                  date_created,
                  description,
                  hall_number,
                  logo_path,
                  seo_description,
                  seo_keywords,
                  seo_title,
                  seo_url,
                  top_banner,
                  url_scheme_image_hall,
                  cinema_id)
VALUES (1,
        '2020-01-01',
        'This is the description of the first hall.',
        '1',
        null,
        'This is the SEO description of the first hall.',
        'This is the SEO keywords of the first hall.',
        'This is the SEO title of the first hall.',
        'first-hall',
        'This is the top banner of the first hall.',
        'This is the url scheme image of the first hall.',
        1),
       (2,
        '2020-01-01',
        'This is the description of the second hall.',
        '2',
        null,
        'This is the SEO description of the second hall.',
        'This is the SEO keywords of the second hall.',
        'This is the SEO title of the second hall.',
        'second-hall',
        'This is the top banner of the second hall.',
        'This is the url scheme image of the second hall.',
        1);

insert into film (id, description, end_premiere_date, link_trailer, main_image, name,
                  seo_description, seo_keywords, seo_title, seo_url, start_premiere_date)
VALUES (1,
        'This is the description of the first film.',
        '2020-01-01',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'This is the main image of the first film.',
        'First Film',
        'This is the SEO description of the first film.',
        'This is the SEO keywords of the first film.',
        'This is the SEO title of the first film.',
        'first-film',
        '2020-01-01'),
       (2,
        'This is the description of the second film.',
        '2020-01-01',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'This is the main image of the second film.',
        'Second Film',
        'This is the SEO description of the second film.',
        'This is the SEO keywords of the second film.',
        'This is the SEO title of the second film.',
        'second-film',
        '2020-01-01');

insert into film_type (film_id, type)
VALUES (1, 'Threedimensional'),
       (1, 'Twodimensional'),
       (2, 'IMAX');


