
#server:
#  port: 8081
#  servlet:
#    context-path: /myapp
#  error:
#    whitelabel:
#      enabled: false

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/kino_cms
#    username: root
#    password: "0000"

#  file:
#    name: "C:\\Users\\Belwerk\\Downloads\\ProjectFiles\\KinoCms-R.Miahkykh\\logs\\kino_cms.log"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slj_kinocms
    username: slj_kinocms
    password: UC7w3mEt57
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB




upload:
  folder:
    path: "/home/slj/projects/KinoCms-R.Miahkykh/uploads"


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

  file:
    name: "/home/slj/projects/KinoCms-R.Miahkykh/logs/kino_cms.log"

  level:
    file: "INFO"
